[build]
  # Build command with dependency resolution
  command = "npm install --legacy-peer-deps --force && npm run build"
  
  # Directory to publish (build output)
  publish = "build"
  
  # Optional: Build environment variables
  [build.environment]
    # Set Node.js version for build
    NODE_VERSION = "18"
    # Optimize for production
    GENERATE_SOURCEMAP = "false"
    # React app environment
    REACT_APP_ENVIRONMENT = "production"
    # NPM configuration to handle peer dependency issues
    NPM_CONFIG_LEGACY_PEER_DEPS = "true"
    NPM_CONFIG_FORCE = "true"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    # Don't cache HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    # Don't cache service worker
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect rules (alternative to _redirects file)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200